version: '3'
services:
  web:
    build: .
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGODB_URI=mongodb://mongo:27017
      - TOKEN_KEY=iReallyLoveCS3219,thisKeyShouldBeKeptPrivateButWePutHereForDemoConvenience
  
  mongo:
    image: mongo:4.2.23-rc1
    volumes:
      - mongovolume:/data/db

volumes:
  mongovolume: